import socket

import oqs

from encryption import decrypt


# Create a socket for the receiver (server)
server = socket.socket()

# Bind the server to localhost on port 5000
server.bind(

        ("localhost",5000)

)

# Start listening for incoming connections
server.listen(1)

print()

print("Receiver Started")

print()

print("Waiting for Sender...")

print()

# Accept connection request from the sender
conn, addr = server.accept()

print("Sender Connected")

print()


# Initialize the ML-KEM-768 algorithm
kem = oqs.KeyEncapsulation(

        "ML-KEM-768"

)

# Generate the public and secret key pair
public_key = kem.generate_keypair()

# Send the public key to the sender
conn.send(public_key)

# Receive the ciphertext generated by the sender
ciphertext = conn.recv(4096)

# Decapsulate the ciphertext to generate the shared secret
shared_secret = kem.decap_secret(

        ciphertext

)

print("Receiver Shared Secret")

print()

# Display the shared secret in hexadecimal format
print(

    shared_secret.hex()

)

print()

# Keep receiving encrypted messages until the session ends
while True:

    # Receive the nonce required for AES decryption
    nonce = conn.recv(16)

    # Exit if the sender closes the connection
    if not nonce:

        break

    # Receive the encrypted message
    encrypted_message = conn.recv(4096)

    # Decrypt the received message using the shared secret
    message = decrypt(

        nonce,

        encrypted_message,

        shared_secret

    )

    # End the session if the sender sends "exit"
    if message.lower() == "exit":

        print()

        print("Sender ended session")

        break

    print()

    print("Message Received")

    print()

    # Display the decrypted message
    print(message)

    print()

# Close the active connection
conn.close()

# Stop the receiver server
server.close()
